// frontend/src/app/layouts/side-bar-layout/side-bar-layout.component.ts
import { Component } from '@angular/core';
import { ButtonModule } from 'primeng/button';
import { MenuItemComponent } from './components/menu-item/menu-item.component';
import { RouterOutlet } from '@angular/router';

@Component({
  selector: 'app-side-bar-layout',
  standalone: true,
  imports: [ButtonModule, MenuItemComponent, RouterOutlet],
  templateUrl: './side-bar-layout.component.html',
  styleUrl: './side-bar-layout.component.css',
})
export class SideBarLayoutComponent {}

<div class="flex flex-row min-h-screen">
  <aside class="w-80 border-r border-gray-300 flex flex-col">
    <h1 class="text-center text-2xl font-semibold py-6">MobiPark</h1>
    <nav class="flex flex-col gap-2 p-2">
      <app-menu-item href="/" [exact]="true" icon="pi pi-home">
        Réserver
      </app-menu-item>

      <app-menu-item href="/my-reservations" icon="pi pi-ticket">
        Mes réservations
      </app-menu-item>

      <app-menu-item href="/my-vehicles" icon="pi pi-car">
        Mes véhicules
      </app-menu-item>
    </nav>
  </aside>

  <div class="flex-1">
    <header class="px-6 py-4 flex justify-end">
      <p-button label="Logout" icon="pi pi-sign-out" severity="secondary" />
    </header>

    <main>
      <router-outlet />
    </main>
  </div>
</div>

// frontend/src/layouts/sidebarLayout.tsx
import { Button, buttonVariants } from "@/components/ui/button";
import { CarIcon, HomeIcon, LogOutIcon, TicketIcon } from "lucide-react";
import { type ReactElement } from "react";
import { Outlet, NavLink, NavLinkProps } from "react-router-dom";

const linkClasses: NavLinkProps["className"] = ({ isActive }) =>
  buttonVariants({
    className: "justify-start gap-x-4",
    variant: isActive ? "default" : "ghost",
  });

export function SidebarLayout(): ReactElement {
  return (
    <div className="flex flex-row min-h-screen">
      <aside className="w-80 border-r flex flex-col">
        <h1 className="p-8 text-center font-bold text-3xl">MobiPark</h1>

        <nav className="flex flex-col gap-y-2 p-4">
          <NavLink className={linkClasses} to="/">
            <HomeIcon className="size-5" />
            Réserver
          </NavLink>
          <NavLink className={linkClasses} to="/my-reservations">
            <TicketIcon className="size-5" />
            Mes réservations
          </NavLink>
          <NavLink className={linkClasses} to="/my-vehicles">
            <CarIcon className="size-5" />
            Mes véhicules
          </NavLink>
        </nav>
      </aside>

      <div className="flex-1">
        <header className="flex flex-row justify-end items-center px-8 py-4">
          <Button variant="ghost" className="gap-x-2">
            <LogOutIcon className="size-5" />
            Logout
          </Button>
        </header>
        <main className="p-4">
          <Outlet />
        </main>
      </div>
    </div>
  );
}
